function [F,j = getstress( rob )
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

for i=rob.N_Q:-1:1
    if i~=1
        % Berechne Kraefte
        F(:,:,i,j) = rob.kl(i).m * rob.kl(i).Bi_ddot_r_s...
        - rob.kl(i).m * rob.kl(i).A_i0 * rob.B0_g...
        - stress.kl(i+1).F;
    
        % Berechne Momente
        stress.kl(i).M = rob.kl(i).I_o * rob.kl(i).Bi_dot_omega +...
        tilde(rob.kl(i).Bi_omega) * rob.kl(i).I_o * rob.kl(i).Bi_omega +...
        rob.kl(i).m * tilde(rob.kl(i).Bi_r_s) * rob.kl(i).Bi_ddot_r_i -...
        rob.kl(i).m * tilde(rob.kl(i).Bi_r_s) * rob.kl(i).A_i0 * rob.B0_g...
        - stress.kl(i+1).M;
    else
        % Berechne Kraefte
        stress.kl(i).F = rob.kl(i).m * rob.kl(i).Bi_ddot_r_s...
        - rob.kl(i).m * rob.kl(i).A_i0 * rob.B0_g;
        
        % Berechne Momente
        stress.kl(i).M = rob.kl(i).I_o * rob.kl(i).Bi_dot_omega +...
        tilde(rob.kl(i).Bi_omega) * rob.kl(i).I_o * rob.kl(i).Bi_omega +...
        rob.kl(i).m * tilde(rob.kl(i).Bi_r_s) * rob.kl(i).Bi_ddot_r_i -...
        rob.kl(i).m * tilde(rob.kl(i).Bi_r_s) * rob.kl(i).A_i0 * rob.B0_g;
    end
end

end

